### ISSUE TITLE
A react native library wrapper

### ISSUE THREAD

**Issue by beast** [liamnichols/UIDevice-PasscodeStatus#12]
Hi there. I am trying to make a universal react native module to check if a device is jailbroken/rooted and if device has screenlock enabled or not. A heads up that I'll wrap your project for checking iOS. Thanks a lot for your great work :)

https://github.com/beast/react-native-isDeviceRooted

**Comment by liamnichols** [comment]
No worries... Although if only targeting iOS 9 or later it might be worth checking out these comments: 

https://github.com/liamnichols/UIDevice-PasscodeStatus/issues/3#issuecomment-190294010

**Comment by beast** [comment]
@liamnichols Thanks again. I added you in the credit. https://github.com/beast/react-native-isDeviceRooted
